# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testti',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activar'),
        ),
    ]
