# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0002_auto_20161004_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='institucion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('HT', 'HETEROSEXUAL'), ('HM', 'HOMOSEXUAL'), ('LE', 'LESBIANA'), ('BI', 'BISEXUAL'), ('IN', 'INDIFERENCIADO')], default='HT', max_length=20, verbose_name='Genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_administrador',
            field=models.BooleanField(default=False, verbose_name='Administrado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_estudiante',
            field=models.BooleanField(default=False, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_psicologo',
            field=models.BooleanField(default=False, verbose_name='Psicologo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='12345', max_length=15, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_docto',
            field=models.CharField(choices=[('CC', 'CEDULA CUIDADANIA'), ('CE', 'CEDULA EXTRANJERIA'), ('PAS', 'PASAPORTE'), ('TI', 'TARJETA IDENTIDAD')], default='TI', max_length=20, verbose_name='Tipo documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='no_docto',
            field=models.CharField(max_length=20, verbose_name='Numero documento'),
        ),
    ]
