# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0002_testti_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntatestti',
            name='numero',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
