# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0003_auto_20161005_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_administrador',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
    ]
