# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0003_auto_20161022_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='testasignado',
            name='estado',
            field=models.CharField(choices=[('SIN INICIAR', 'SIN INICIAR'), ('INICIADO', 'INICIADO'), ('FINALIZADO', 'FINALIZADO'), ('DIAGNOSTICADO', 'DIAGNOSTICADO')], default=2, max_length=200),
            preserve_default=False,
        ),
    ]
