# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0004_auto_20161005_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='psicologo',
            options={'verbose_name': 'Psicologo', 'verbose_name_plural': 'Psicologos'},
        ),
    ]
