# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0005_auto_20161023_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ptti.Psicologo'),
        ),
    ]
