# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0005_auto_20161005_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
