# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0006_auto_20161023_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testasignado',
            name='estado',
            field=models.CharField(choices=[('SIN INICIAR', 'SIN INICIAR'), ('INICIADO', 'INICIADO'), ('FINALIZADO', 'FINALIZADO'), ('DIAGNOSTICADO', 'DIAGNOSTICADO')], default='SIN INICIAR', max_length=200),
        ),
    ]
