# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0006_auto_20161005_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
