# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0007_auto_20161104_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestaestudiante',
            old_name='test',
            new_name='testAsignado',
        ),
    ]
