# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0008_auto_20161108_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntatestti',
            name='numero',
            field=models.CharField(max_length=200),
        ),
    ]
