# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0008_auto_20161009_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_docto',
            field=models.CharField(choices=[('CEDULA CUIDADANIA', 'CEDULA CUIDADANIA'), ('CEDULA EXTRANJERIA', 'CEDULA EXTRANJERIA'), ('PASAPORTE', 'PASAPORTE'), ('TARJETA IDENTIDAD', 'TARJETA IDENTIDAD')], max_length=20, verbose_name='Tipo documento'),
        ),
    ]
