# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0009_auto_20161109_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='testti',
            name='no_preguntas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preguntatestti',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
