# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0011_auto_20161109_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='testasignado',
            name='pre_actual',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
