# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0012_testasignado_pre_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='testti',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testti',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
