# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0013_auto_20161109_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestaestudiante',
            options={'verbose_name': 'Respuesta Estudiante', 'verbose_name_plural': 'Respuestas Estudiantes'},
        ),
    ]
