# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0014_auto_20161109_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaestudiante',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ptti.RespuestaTestTI'),
        ),
    ]
